# Generated by Django 4.2.13 on 2024-05-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0003_problem_timestamp_alter_problem_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='accepted',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
